monsters = {
    "Leviathan": "Gargantuan",
    "Ancient Copper Dragon": "Gargantuan",
    "Roc": "Gargantuan",
    "Phoenix": "Gargantuan",
    "Ancient Silver Dragon": "Gargantuan",
    "Kraken": "Gargantuan",
    "Ancient White Dragon": "Gargantuan",
    "Ancient Bronze Dragon": "Gargantuan",
    "Astral Dreadnought": "Gargantuan",
    "Purple Worm": "Gargantuan",
    "Tarrasque": "Gargantuan",
    "Brontosaurus": "Gargantuan",
    "Zaratan": "Gargantuan",
    "Dragon Turtle": "Gargantuan",
    "Ancient Brass Dragon": "Gargantuan",
    "Ancient Red Dragon": "Gargantuan",
    "Elder Tempest": "Gargantuan",
    "Ancient Gold Dragon": "Gargantuan",
    "Ancient Blue Dragon": "Gargantuan",
    "Ancient Green Dragon": "Gargantuan",
    "Ancient Black Dragon": "Gargantuan",
    "Neothelid": "Gargantuan",
    "Mouth of Grolantor": "Huge",
    "Adult Silver Dragon": "Huge",
    "Giant Constrictor Snake": "Huge",
    "Sibriex": "Huge",
    "Hill Giant": "Huge",
    "Stegosaurus": "Huge",
    "Nightwalker": "Huge",
    "Adult Bronze Dragon": "Huge",
    "Stone Giant": "Huge",
    "Awakened Tree": "Huge",
    "Adult Black Dragon": "Huge",
    "Tyrannosaurus Rex": "Huge",
    "Adult White Dragon": "Huge",
    "Adult Blue Dracolich": "Huge",
    "Elder Oblex": "Huge",
    "Ki-rin": "Huge",
    "Balor": "Huge",
    "Adult Green Dragon": "Huge",
    "Mammoth": "Huge",
    "Empyrean": "Huge",
    "Treant": "Huge",
    "Giant Shark": "Huge",
    "Giant Ape": "Huge",
    "Fire Giant": "Huge",
    "Storm Giant Quintessent": "Huge",
    "Frost Giant Everlasting One": "Huge",
    "Goristro": "Huge",
    "Yuan-ti Anathema": "Huge",
    "Remorhaz": "Huge",
    "Hydra": "Huge",
    "Froghemoth": "Huge",
    "Cloud Giant Smiling One": "Huge",
    "Killer Whale": "Huge",
    "Ankylosaurus": "Huge",
    "Molydeus": "Huge",
    "Adult Brass Dragon": "Huge",
    "Cyclops": "Huge",
    "Fomorian": "Huge",
    "Triceratops": "Huge",
    "Storm Giant": "Huge",
    "Fire Giant Dreadnought": "Huge",
    "Giant Elk": "Huge",
    "Adult Blue Dragon": "Huge",
    "Adult Gold Dragon": "Huge",
    "Hellfire Engine": "Huge",
    "Quetzalcoatlus": "Huge",
    "Frost Giant": "Huge",
    "Stone Giant Dreamwalker": "Huge",
    "Abominable Yeti": "Huge",
    "Adult Copper Dragon": "Huge",
    "Giant Crocodile": "Huge",
    "Adult Red Dragon": "Huge",
    "Cloud Giant": "Huge",
    "Dire Troll": "Huge",
    "Elephant": "Huge",
    "Frost Salamander": "Huge",
    "Behir": "Huge",
    "Winter Wolf": "Large",
    "Cadaver Collector": "Large",
    "Otyugh": "Large",
    "Giant Scorpion": "Large",
    "Young Remorhaz": "Large",
    "Displacer Beast": "Large",
    "Hunter Shark": "Large",
    "Wastrilith": "Large",
    "Lion": "Large",
    "Shoosuva": "Large",
    "Death Tyrant": "Large",
    "Rug of Smothering": "Large",
    "Tlincalli": "Large",
    "Merrow": "Large",
    "Dao": "Large",
    "Beholder Zombie": "Large",
    "Ettin": "Large",
    "Griffon": "Large",
    "Glabrezu": "Large",
    "Gynosphinx": "Large",
    "Venom Troll": "Large",
    "Myconid Sovereign": "Large",
    "Armanite": "Large",
    "Elk": "Large",
    "Young Red Shadow Dragon": "Large",
    "Yuan-ti Abomination": "Large",
    "Pegasus": "Large",
    "Chuul": "Large",
    "Giant Sea Horse": "Large",
    "Death Kiss": "Large",
    "Retriever": "Large",
    "Blue Slaad": "Large",
    "Barlgura": "Large",
    "Giant Toad": "Large",
    "Marut": "Large",
    "Stench Kow": "Large",
    "Young Green Dragon": "Large",
    "Mindwitness": "Large",
    "Rot Troll": "Large",
    "Allosaurus": "Large",
    "Gas Spore": "Large",
    "Giant Spider": "Large",
    "Giant Bat": "Large",
    "Marilith": "Large",
    "Death Tyrant (in lair)": "Large",
    "Nightmare": "Large",
    "Shambling Mound": "Large",
    "Giant Goat": "Large",
    "Barghest": "Large",
    "Efreeti": "Large",
    "Saber-toothed Tiger": "Large",
    "Polar Bear": "Large",
    "Ox": "Large",
    "Kruthik Hive Lord": "Large",
    "Young Red Dragon": "Large",
    "Crocodile": "Large",
    "Nalfeshnee": "Large",
    "Giant Strider": "Large",
    "Ogre Zombie": "Large",
    "Dire Wolf": "Large",
    "Djinni": "Large",
    "Spirit Troll": "Large",
    "Sahuagin Baron": "Large",
    "Camel": "Large",
    "Female Steeder": "Large",
    "Giant Eagle": "Large",
    "Axe Beak": "Large",
    "Steel Predator": "Large",
    "Guardian Naga": "Large",
    "Catoblepas": "Large",
    "Flail Snail": "Large",
    "Air Elemental": "Large",
    "Corpse Flower": "Large",
    "Pentadrone": "Large",
    "Warhorse": "Large",
    "Owlbear": "Large",
    "Pit Fiend": "Large",
    "Earth Elemental": "Large",
    "Trapper": "Large",
    "Manticore": "Large",
    "Young Brass Dragon": "Large",
    "Young Blue Dragon": "Large",
    "Balhannoth": "Large",
    "Ogre Battering Ram": "Large",
    "Tiger": "Large",
    "Troll": "Large",
    "Yeth Hound": "Large",
    "Iron Golem": "Large",
    "Young Gold Dragon": "Large",
    "Banderhobb": "Large",
    "Young Black Dragon": "Large",
    "Minotaur Skeleton": "Large",
    "Ochre Jelly": "Large",
    "Plesiosaurus": "Large",
    "Howler": "Large",
    "Stone Golem": "Large",
    "Fire Elemental": "Large",
    "Worg": "Large",
    "Water Weird": "Large",
    "Star Spawn Hulk": "Large",
    "Ice Devil": "Large",
    "Centaur": "Large",
    "Young White Dragon": "Large",
    "Planetar": "Large",
    "Carrion Crawler": "Large",
    "Hippogriff": "Large",
    "Rhinoceros": "Large",
    "Young Bronze Dragon": "Large",
    "Warhorse Skeleton": "Large",
    "Hook Horror": "Large",
    "Draft Horse": "Large",
    "Androsphinx": "Large",
    "Salamander": "Large",
    "Boneclaw": "Large",
    "Chasme": "Large",
    "Chimera": "Large",
    "Giant Hyena": "Large",
    "Bone Naga": "Large",
    "Ogre Chain Brute": "Large",
    "Lamia": "Large",
    "Ogre": "Large",
    "Giant Octopus": "Large",
    "Horned Devil": "Large",
    "Yeti": "Large",
    "Cow": "Large",
    "Minotaur": "Large",
    "Phase Spider": "Large",
    "Solar": "Large",
    "Draegloth": "Large",
    "Oni": "Large",
    "Water Elemental": "Large",
    "Vrock": "Large",
    "Marid": "Large",
    "Gray Render": "Large",
    "Bone Devil": "Large",
    "Aurochs": "Large",
    "Ankheg": "Large",
    "Wyvern": "Large",
    "Annis Hag": "Large",
    "Aboleth": "Large",
    "Riding Horse": "Large",
    "Hezrou": "Large",
    "Yagnoloth": "Large",
    "Cave Bear": "Large",
    "Gelatinous Cube": "Large",
    "Constrictor Snake": "Large",
    "Red Slaad": "Large",
    "Devourer": "Large",
    "Bulette": "Large",
    "Elder Brain": "Large",
    "Black Pudding": "Large",
    "Girallon": "Large",
    "Unicorn": "Large",
    "Spirit Naga": "Large",
    "Beholder": "Large",
    "Umber Hulk": "Large",
    "Roper": "Large",
    "Ogre Howdah": "Large",
    "Nycaloth": "Large",
    "Beholder (in lair)": "Large",
    "Ulitharid": "Large",
    "Young Silver Dragon": "Large",
    "Hadrosaurus": "Large",
    "Young Copper Dragon": "Large",
    "Shield Guardian": "Large",
    "Half-ogre": "Large",
    "Giant Lizard": "Large",
    "Drider": "Large",
    "Ogre Bolt Launcher": "Large",
    "Leucrotta": "Large",
    "Grick Alpha": "Large",
    "Giant Owl": "Large",
    "Giant Vulture": "Large",
    "Clay Golem": "Large",
    "Green Slaad": "Large",
    "Rothe": "Large",
    "Orthon": "Large",
    "Cloaker": "Large",
    "Giant Boar": "Large",
    "Gorgon": "Large",
    "Brown Bear": "Large",
    "Hell Hound": "Medium",
    "Basilisk": "Medium",
    "Brass Dragon Wyrmling": "Medium",
    "Swarm of Rot Grubs": "Medium",
    "Green Abishai": "Medium",
    "Wereboar": "Medium",
    "Firenewt Warlock of Imix": "Medium",
    "Drow Matron Mother": "Medium",
    "Blink Dog": "Medium",
    "Duergar Despot": "Medium",
    "Specter": "Medium",
    "Wolf": "Medium",
    "Oaken Bolter": "Medium",
    "Lost Sorrowsworn": "Medium",
    "Drow Favored Consort": "Medium",
    "Hydroloth": "Medium",
    "Hobgoblin Iron Shadow": "Medium",
    "Violet Fungus": "Medium",
    "Winter Eladrin": "Medium",
    "Satyr": "Medium",
    "Chain Devil": "Medium",
    "Cave Fisher": "Medium",
    "Death Knight": "Medium",
    "Drow Mage": "Medium",
    "Drow Priestess of Lolth": "Medium",
    "Gauth": "Medium",
    "Drow Elite Warrior": "Medium",
    "Swarm of Bats": "Medium",
    "Rakshasa": "Medium",
    "Orc War Chief": "Medium",
    "Lonely Sorrowsworn": "Medium",
    "Gnoll Flesh Gnawer": "Medium",
    "Dimetrodon": "Medium",
    "Soul Monger": "Medium",
    "Green Dragon Wyrmling": "Medium",
    "Wood Woad": "Medium",
    "Panther": "Medium",
    "Banshee": "Medium",
    "Yochlol": "Medium",
    "Spawn of Kyuss": "Medium",
    "Orc Nurtured One of Yurtrus": "Medium",
    "Animated Armor": "Medium",
    "Githyanki Supreme Commander": "Medium",
    "Galeb Duhr": "Medium",
    "Thorny": "Medium",
    "Star Spawn Seer": "Medium",
    "Shrieker": "Medium",
    "Mind Flayer Lich": "Medium",
    "Invisible Stalker": "Medium",
    "Swarm of Poisonous Snakes": "Medium",
    "Sahuagin": "Medium",
    "Mind Flayer Arcanist": "Medium",
    "Bodak": "Medium",
    "Fire Snake": "Medium",
    "Bronze Dragon Wyrmling": "Medium",
    "Deer": "Medium",
    "Nagpa": "Medium",
    "Gnoll Hunter": "Medium",
    "Quaggoth Spore Servant": "Medium",
    "Lemure": "Medium",
    "Adult Kruthik": "Medium",
    "Darkling Elder": "Medium",
    "Mule": "Medium",
    "Hobgoblin": "Medium",
    "Morkoth (in lair)": "Medium",
    "Deva": "Medium",
    "Needle Blight": "Medium",
    "Ghost": "Medium",
    "Sword Wraith Commander": "Medium",
    "Dybbuk": "Medium",
    "Duergar": "Medium",
    "Shadow Dancer": "Medium",
    "Thri-kreen": "Medium",
    "Duergar Screamer": "Medium",
    "Merfolk": "Medium",
    "Sea Spawn": "Medium",
    "Shadow": "Medium",
    "Giant Weasel": "Medium",
    "Kuo-toa Archpriest": "Medium",
    "Bheur Hag": "Medium",
    "Guard Drake": "Medium",
    "Stone Defender": "Medium",
    "Duergar Stone Guard": "Medium",
    "Kuo-toa Whip": "Medium",
    "Ettercap": "Medium",
    "Summer Eladrin": "Medium",
    "Abyssal Wretch": "Medium",
    "Orc Red Fang of Shargaas": "Medium",
    "Lizardfolk": "Medium",
    "Quaggoth Thonot": "Medium",
    "Deathlock": "Medium",
    "Lich": "Medium",
    "Babau": "Medium",
    "Mimic": "Medium",
    "Eidolon": "Medium",
    "Skeleton": "Medium",
    "White Abishai": "Medium",
    "Mastiff": "Medium",
    "Githyanki Knight": "Medium",
    "Slithering Tracker": "Medium",
    "Grell": "Medium",
    "Ghast": "Medium",
    "Harpy": "Medium",
    "Githzerai Enlightened": "Medium",
    "Tridrone": "Medium",
    "Hyena": "Medium",
    "Orc Claw of Luthic": "Medium",
    "Wererat": "Medium",
    "Nupperibo": "Medium",
    "Spectator": "Medium",
    "Gnoll Fang of Yeenoghu": "Medium",
    "Pteranodon": "Medium",
    "Red Abishai": "Medium",
    "Blue Abishai": "Medium",
    "Alhoon": "Medium",
    "Specter (poltergeist)": "Medium",
    "Star Spawn Mangler": "Medium",
    "Deep Rothe": "Medium",
    "Githyanki Warrior": "Medium",
    "Lizardfolk Shaman": "Medium",
    "Yuan-ti Malison": "Medium",
    "Orc Hand of Yurtrus": "Medium",
    "Skull Lord": "Medium",
    "Grick": "Medium",
    "Hungry Sorrowsworn": "Medium",
    "Hobgoblin Warlord": "Medium",
    "Flesh Golem": "Medium",
    "Stone Cursed": "Medium",
    "Earth Elemental Myrmidon": "Medium",
    "Revenant": "Medium",
    "Reef Shark": "Medium",
    "Githyanki Gish": "Medium",
    "Drow": "Medium",
    "Hobgoblin Captain": "Medium",
    "Gray Ooze": "Medium",
    "Sahuagin Priestess": "Medium",
    "Tanarukk": "Medium",
    "Tortle": "Medium",
    "Giant Wolf Spider": "Medium",
    "Black Abishai": "Medium",
    "Deathlock Mastermind": "Medium",
    "Shadow Demon": "Medium",
    "Morkoth": "Medium",
    "Copper Dragon Wyrmling": "Medium",
    "Drow Arachnomancer": "Medium",
    "Maw Demon": "Medium",
    "Vulture": "Medium",
    "Medusa": "Medium",
    "Shadow Mastiff": "Medium",
    "Vampire (warrior)": "Medium",
    "Fire Elemental Myrmidon": "Medium",
    "Alkilith": "Medium",
    "Swarm of Rats": "Medium",
    "Maurezhi": "Medium",
    "Giant Badger": "Medium",
    "Yuan-ti Pureblood": "Medium",
    "Swarm of Ravens": "Medium",
    "Deep Scion": "Medium",
    "Couatl": "Medium",
    "Piercer": "Medium",
    "Incubus": "Medium",
    "Yuan-ti Pit Master": "Medium",
    "Bugbear Chief": "Medium",
    "Green Hag": "Medium",
    "Death Dog": "Medium",
    "Drow House Captain": "Medium",
    "Air Elemental Myrmidon": "Medium",
    "Orc": "Medium",
    "Gnoll Witherling": "Medium",
    "Arcanaloth": "Medium",
    "Deinonychus": "Medium",
    "Gargoyle": "Medium",
    "Water Elemental Myrmidon": "Medium",
    "Nothic": "Medium",
    "Helmed Horror": "Medium",
    "Githyanki Kith'rak": "Medium",
    "Blue Dragon Wyrmling": "Medium",
    "Vampiric Mist": "Medium",
    "Bulezau": "Medium",
    "Neogi Master": "Medium",
    "Death Slaad": "Medium",
    "Yuan-ti Nightmare Speaker": "Medium",
    "Canoloth": "Medium",
    "Yuan-ti Mind Whisperer": "Medium",
    "Sea Hag": "Medium",
    "Spring Eladrin": "Medium",
    "Azer": "Medium",
    "Kuo-toa": "Medium",
    "Night Hag": "Medium",
    "Drow Shadowblade": "Medium",
    "Pony": "Medium",
    "Boar": "Medium",
    "Drow Inquisitor": "Medium",
    "Bullywug": "Medium",
    "Gray Slaad": "Medium",
    "Githzerai Anarch": "Medium",
    "Sword Wraith Warrior": "Medium",
    "Vampire Spawn": "Medium",
    "Skulk": "Medium",
    "Gloom Weaver": "Medium",
    "Goat": "Medium",
    "Choldrith": "Medium",
    "Xorn": "Medium",
    "Dolphin": "Medium",
    "Nabassu": "Medium",
    "Duergar Warlord": "Medium",
    "Giant Frog": "Medium",
    "Angry Sorrowsworn": "Medium",
    "Swarm of Insects": "Medium",
    "Red Dragon Wyrmling": "Medium",
    "Dryad": "Medium",
    "Duergar Soulblade": "Medium",
    "Ape": "Medium",
    "Peryton": "Medium",
    "Jackalwere": "Medium",
    "Amnizu": "Medium",
    "Firenewt Warrior": "Medium",
    "Ghoul": "Medium",
    "Mezzoloth": "Medium",
    "Oinoloth": "Medium",
    "Star Spawn Larva Mage": "Medium",
    "Silver Dragon Wyrmling": "Medium",
    "Mummy Lord": "Medium",
    "Quaggoth": "Medium",
    "Duodrone": "Medium",
    "Giant Wasp": "Medium",
    "Iron Cobra": "Medium",
    "Zombie": "Medium",
    "Aarakocra": "Medium",
    "Rust Monster": "Medium",
    "Half-Red Dragon Veteran": "Medium",
    "Gnoll": "Medium",
    "Black Bear": "Medium",
    "Duergar Mind Master": "Medium",
    "Vine Blight": "Medium",
    "Orc Eye of Gruumsh": "Medium",
    "Giant Crab": "Medium",
    "Yuan-ti Broodguard": "Medium",
    "Vampire": "Medium",
    "Male Steeder": "Medium",
    "Adult Oblex": "Medium",
    "Werebear": "Medium",
    "Duergar Xarrorn": "Medium",
    "Orog": "Medium",
    "Lich (in lair)": "Medium",
    "Erinyes": "Medium",
    "Mind Flayer": "Medium",
    "Cambion": "Medium",
    "Troglodyte": "Medium",
    "Kenku": "Medium",
    "Myconid Adult": "Medium",
    "Wraith": "Medium",
    "Mummy Lord (in lair)": "Medium",
    "Bronze Scout": "Medium",
    "Gibbering Mouther": "Medium",
    "Rutterkin": "Medium",
    "Grimlock": "Medium",
    "Black Dragon Wyrmling": "Medium",
    "Wight": "Medium",
    "Githzerai Zerth": "Medium",
    "Swarm of Quippers": "Medium",
    "Weretiger": "Medium",
    "Deathlock Wight": "Medium",
    "Mummy": "Medium",
    "Githzerai Monk": "Medium",
    "Lizard King/Queen": "Medium",
    "Orc Blade of Ilneval": "Medium",
    "Allip": "Medium",
    "Giant Poisonous Snake": "Medium",
    "Duergar Kavalrachni": "Medium",
    "Barbed Devil": "Medium",
    "Merrenoloth": "Medium",
    "Dhergoloth": "Medium",
    "Bugbear": "Medium",
    "Gold Dragon Wyrmling": "Medium",
    "Succubus": "Medium",
    "White Dragon Wyrmling": "Medium",
    "Tortle Druid": "Medium",
    "Meazel": "Medium",
    "Hobgoblin Devastator": "Medium",
    "Autumn Eladrin": "Medium",
    "Giff": "Medium",
    "Swarm of Cranium Rats": "Medium",
    "Werewolf": "Medium",
    "Scarecrow": "Medium",
    "Flind": "Medium",
    "Merregon": "Medium",
    "Vampire (spellcaster)": "Medium",
    "Bearded Devil": "Medium",
    "Narzugon": "Medium",
    "Duergar Hammerer": "Medium",
    "Ultroloth": "Medium",
    "Monodrone": "Medium",
    "Quadrone": "Medium",
    "Gnoll Pack Lord": "Medium",
    "Berbalang": "Medium",
    "Doppelganger": "Medium",
    "Grung": "Small",
    "Manes": "Small",
    "Derro": "Small",
    "Myconid Sprout": "Small",
    "Ice Mephit": "Small",
    "Goblin Boss": "Small",
    "Baboon": "Small",
    "Giant Fire Beetle": "Small",
    "Awakened Shrub": "Small",
    "Kobold Dragonshield": "Small",
    "Octopus": "Small",
    "Korred": "Small",
    "Derro Savant": "Small",
    "Goblin": "Small",
    "Darkmantle": "Small",
    "Dretch": "Small",
    "Kobold Inventor": "Small",
    "Blood Hawk": "Small",
    "Wretched Sorrowsworn": "Small",
    "Winged Kobold": "Small",
    "Boggle": "Small",
    "Kobold Scale Sorcerer": "Small",
    "Smoke Mephit": "Small",
    "Neogi": "Small",
    "Meenlock": "Small",
    "Giant Rat": "Small",
    "Redcap": "Small",
    "Steam Mephit": "Small",
    "Star Spawn Grue": "Small",
    "Grung Elite Warrior": "Small",
    "Magma Mephit": "Small",
    "Young Kruthik": "Small",
    "Kobold": "Small",
    "Grung Wildling": "Small",
    "Magmin": "Small",
    "Mud Mephit": "Small",
    "Flying Sword": "Small",
    "Jackal": "Small",
    "Nilbog": "Small",
    "Eagle": "Small",
    "Darkling": "Small",
    "Choker": "Small",
    "Chitine": "Small",
    "Vegepygmy": "Small",
    "Spined Devil": "Small",
    "Xvart": "Small",
    "Flumph": "Small",
    "Xvart Warlock of Raxivort": "Small",
    "Twig Blight": "Small",
    "Vegepygmy Chief": "Small",
    "Dust Mephit": "Small",
    "Svirfneblin": "Small",
    "Giant Centipede": "Small",
    "Cockatrice": "Small",
    "Cat": "Tiny",
    "Intellect Devourer": "Tiny",
    "Young Faerie Dragon": "Tiny",
    "Pixie": "Tiny",
    "Imp": "Tiny",
    "Vargouille": "Tiny",
    "Weasel": "Tiny",
    "Adult Faerie Dragon": "Tiny",
    "Raven": "Tiny",
    "Gazer": "Tiny",
    "Quasit": "Tiny",
    "Crab": "Tiny",
    "Bat": "Tiny",
    "Sprite": "Tiny",
    "Badger": "Tiny",
    "Crawling Claw": "Tiny",
    "Demilich": "Tiny",
    "Oblex Spawn": "Tiny",
    "Neogi Hatchling": "Tiny",
    "Frog": "Tiny",
    "Lizard": "Tiny",
    "Cranium Rat": "Tiny",
    "Will-o-wisp": "Tiny",
    "Demilich (in lair)": "Tiny",
    "Pseudodragon": "Tiny",
    "Homunculus": "Tiny",
    "Quipper": "Tiny",
    "Sea Horse": "Tiny",
    "Spider": "Tiny",
    "Velociraptor": "Tiny",
    "Flying Snake": "Tiny",
    "Scorpion": "Tiny",
    "Rat": "Tiny",
    "Poisonous Snake": "Tiny",
    "Flameskull": "Tiny",
    "Quickling": "Tiny",
    "Hawk": "Tiny",
    "Stirge": "Tiny",
    "Owl": "Tiny",
    "Slaad Tadpole": "Tiny"
}


gargantuan_monsters = {
    "Leviathan": "Gargantuan",
    "Ancient Copper Dragon": "Gargantuan",
    "Roc": "Gargantuan",
    "Phoenix": "Gargantuan",
    "Ancient Silver Dragon": "Gargantuan",
    "Kraken": "Gargantuan",
    "Ancient White Dragon": "Gargantuan",
    "Ancient Bronze Dragon": "Gargantuan",
    "Astral Dreadnought": "Gargantuan",
    "Purple Worm": "Gargantuan",
    "Tarrasque": "Gargantuan",
    "Brontosaurus": "Gargantuan",
    "Zaratan": "Gargantuan",
    "Dragon Turtle": "Gargantuan",
    "Ancient Brass Dragon": "Gargantuan",
    "Ancient Red Dragon": "Gargantuan",
    "Elder Tempest": "Gargantuan",
    "Ancient Gold Dragon": "Gargantuan",
    "Ancient Blue Dragon": "Gargantuan",
    "Ancient Green Dragon": "Gargantuan",
    "Ancient Black Dragon": "Gargantuan",
    "Neothelid": "Gargantuan"
}

huge_monsters = {
    "Mouth of Grolantor": "Huge",
    "Adult Silver Dragon": "Huge",
    "Giant Constrictor Snake": "Huge",
    "Sibriex": "Huge",
    "Hill Giant": "Huge",
    "Stegosaurus": "Huge",
    "Nightwalker": "Huge",
    "Adult Bronze Dragon": "Huge",
    "Stone Giant": "Huge",
    "Awakened Tree": "Huge",
    "Adult Black Dragon": "Huge",
    "Tyrannosaurus Rex": "Huge",
    "Adult White Dragon": "Huge",
    "Adult Blue Dracolich": "Huge",
    "Elder Oblex": "Huge",
    "Ki-rin": "Huge",
    "Balor": "Huge",
    "Adult Green Dragon": "Huge",
    "Mammoth": "Huge",
    "Empyrean": "Huge",
    "Treant": "Huge",
    "Giant Shark": "Huge",
    "Giant Ape": "Huge",
    "Fire Giant": "Huge",
    "Storm Giant Quintessent": "Huge",
    "Frost Giant Everlasting One": "Huge",
    "Goristro": "Huge",
    "Yuan-ti Anathema": "Huge",
    "Remorhaz": "Huge",
    "Hydra": "Huge",
    "Froghemoth": "Huge",
    "Cloud Giant Smiling One": "Huge",
    "Killer Whale": "Huge",
    "Ankylosaurus": "Huge",
    "Molydeus": "Huge",
    "Adult Brass Dragon": "Huge",
    "Cyclops": "Huge",
    "Fomorian": "Huge",
    "Triceratops": "Huge",
    "Storm Giant": "Huge",
    "Fire Giant Dreadnought": "Huge",
    "Giant Elk": "Huge",
    "Adult Blue Dragon": "Huge",
    "Adult Gold Dragon": "Huge",
    "Hellfire Engine": "Huge",
    "Quetzalcoatlus": "Huge",
    "Frost Giant": "Huge",
    "Stone Giant Dreamwalker": "Huge",
    "Abominable Yeti": "Huge",
    "Adult Copper Dragon": "Huge",
    "Giant Crocodile": "Huge",
    "Adult Red Dragon": "Huge",
    "Cloud Giant": "Huge",
    "Dire Troll": "Huge",
    "Elephant": "Huge",
    "Frost Salamander": "Huge",
    "Behir": "Huge"
}

large_monsters = {
    "Winter Wolf": "Large",
    "Cadaver Collector": "Large",
    "Otyugh": "Large",
    "Giant Scorpion": "Large",
    "Young Remorhaz": "Large",
    "Displacer Beast": "Large",
    "Hunter Shark": "Large",
    "Wastrilith": "Large",
    "Lion": "Large",
    "Shoosuva": "Large",
    "Death Tyrant": "Large",
    "Rug of Smothering": "Large",
    "Tlincalli": "Large",
    "Merrow": "Large",
    "Dao": "Large",
    "Beholder Zombie": "Large",
    "Ettin": "Large",
    "Griffon": "Large",
    "Glabrezu": "Large",
    "Gynosphinx": "Large",
    "Venom Troll": "Large",
    "Myconid Sovereign": "Large",
    "Armanite": "Large",
    "Elk": "Large",
    "Young Red Shadow Dragon": "Large",
    "Yuan-ti Abomination": "Large",
    "Pegasus": "Large",
    "Chuul": "Large",
    "Giant Sea Horse": "Large",
    "Death Kiss": "Large",
    "Retriever": "Large",
    "Blue Slaad": "Large",
    "Barlgura": "Large",
    "Giant Toad": "Large",
    "Marut": "Large",
    "Stench Kow": "Large",
    "Young Green Dragon": "Large",
    "Mindwitness": "Large",
    "Rot Troll": "Large",
    "Allosaurus": "Large",
    "Gas Spore": "Large",
    "Giant Spider": "Large",
    "Giant Bat": "Large",
    "Marilith": "Large",
    "Death Tyrant (in lair)": "Large",
    "Nightmare": "Large",
    "Shambling Mound": "Large",
    "Giant Goat": "Large",
    "Barghest": "Large",
    "Efreeti": "Large",
    "Saber-toothed Tiger": "Large",
    "Polar Bear": "Large",
    "Ox": "Large",
    "Kruthik Hive Lord": "Large",
    "Young Red Dragon": "Large",
    "Crocodile": "Large",
    "Nalfeshnee": "Large",
    "Giant Strider": "Large",
    "Ogre Zombie": "Large",
    "Dire Wolf": "Large",
    "Djinni": "Large",
    "Spirit Troll": "Large",
    "Sahuagin Baron": "Large",
    "Camel": "Large",
    "Female Steeder": "Large",
    "Giant Eagle": "Large",
    "Axe Beak": "Large",
    "Steel Predator": "Large",
    "Guardian Naga": "Large",
    "Catoblepas": "Large",
    "Flail Snail": "Large",
    "Air Elemental": "Large",
    "Corpse Flower": "Large",
    "Pentadrone": "Large",
    "Warhorse": "Large",
    "Owlbear": "Large",
    "Pit Fiend": "Large",
    "Earth Elemental": "Large",
    "Trapper": "Large",
    "Manticore": "Large",
    "Young Brass Dragon": "Large",
    "Young Blue Dragon": "Large",
    "Balhannoth": "Large",
    "Ogre Battering Ram": "Large",
    "Tiger": "Large",
    "Troll": "Large",
    "Yeth Hound": "Large",
    "Iron Golem": "Large",
    "Young Gold Dragon": "Large",
    "Banderhobb": "Large",
    "Young Black Dragon": "Large",
    "Minotaur Skeleton": "Large",
    "Ochre Jelly": "Large",
    "Plesiosaurus": "Large",
    "Howler": "Large",
    "Stone Golem": "Large",
    "Fire Elemental": "Large",
    "Worg": "Large",
    "Water Weird": "Large",
    "Star Spawn Hulk": "Large",
    "Ice Devil": "Large",
    "Centaur": "Large",
    "Young White Dragon": "Large",
    "Planetar": "Large",
    "Carrion Crawler": "Large",
    "Hippogriff": "Large",
    "Rhinoceros": "Large",
    "Young Bronze Dragon": "Large",
    "Warhorse Skeleton": "Large",
    "Hook Horror": "Large",
    "Draft Horse": "Large",
    "Androsphinx": "Large",
    "Salamander": "Large",
    "Boneclaw": "Large",
    "Chasme": "Large",
    "Chimera": "Large",
    "Giant Hyena": "Large",
    "Bone Naga": "Large",
    "Ogre Chain Brute": "Large",
    "Lamia": "Large",
    "Ogre": "Large",
    "Giant Octopus": "Large",
    "Horned Devil": "Large",
    "Yeti": "Large",
    "Cow": "Large",
    "Minotaur": "Large",
    "Phase Spider": "Large",
    "Solar": "Large",
    "Draegloth": "Large",
    "Oni": "Large",
    "Water Elemental": "Large",
    "Vrock": "Large",
    "Marid": "Large",
    "Gray Render": "Large",
    "Bone Devil": "Large",
    "Aurochs": "Large",
    "Ankheg": "Large",
    "Wyvern": "Large",
    "Annis Hag": "Large",
    "Aboleth": "Large",
    "Riding Horse": "Large",
    "Hezrou": "Large",
    "Yagnoloth": "Large",
    "Cave Bear": "Large",
    "Gelatinous Cube": "Large",
    "Constrictor Snake": "Large",
    "Red Slaad": "Large",
    "Devourer": "Large",
    "Bulette": "Large",
    "Elder Brain": "Large",
    "Black Pudding": "Large",
    "Girallon": "Large",
    "Unicorn": "Large",
    "Spirit Naga": "Large",
    "Beholder": "Large",
    "Umber Hulk": "Large",
    "Roper": "Large",
    "Ogre Howdah": "Large",
    "Nycaloth": "Large",
    "Beholder (in lair)": "Large",
    "Ulitharid": "Large",
    "Young Silver Dragon": "Large",
    "Hadrosaurus": "Large",
    "Young Copper Dragon": "Large",
    "Shield Guardian": "Large",
    "Half-ogre": "Large",
    "Giant Lizard": "Large",
    "Drider": "Large",
    "Ogre Bolt Launcher": "Large",
    "Leucrotta": "Large",
    "Grick Alpha": "Large",
    "Giant Owl": "Large",
    "Giant Vulture": "Large",
    "Clay Golem": "Large",
    "Green Slaad": "Large",
    "Rothe": "Large",
    "Orthon": "Large",
    "Cloaker": "Large",
    "Giant Boar": "Large",
    "Gorgon": "Large",
    "Brown Bear": "Large"
}

medium_monsters = {
    "Hell Hound": "Medium",
    "Basilisk": "Medium",
    "Brass Dragon Wyrmling": "Medium",
    "Swarm of Rot Grubs": "Medium",
    "Green Abishai": "Medium",
    "Wereboar": "Medium",
    "Firenewt Warlock of Imix": "Medium",
    "Drow Matron Mother": "Medium",
    "Blink Dog": "Medium",
    "Duergar Despot": "Medium",
    "Specter": "Medium",
    "Wolf": "Medium",
    "Oaken Bolter": "Medium",
    "Lost Sorrowsworn": "Medium",
    "Drow Favored Consort": "Medium",
    "Hydroloth": "Medium",
    "Hobgoblin Iron Shadow": "Medium",
    "Violet Fungus": "Medium",
    "Winter Eladrin": "Medium",
    "Satyr": "Medium",
    "Chain Devil": "Medium",
    "Cave Fisher": "Medium",
    "Death Knight": "Medium",
    "Drow Mage": "Medium",
    "Drow Priestess of Lolth": "Medium",
    "Gauth": "Medium",
    "Drow Elite Warrior": "Medium",
    "Swarm of Bats": "Medium",
    "Rakshasa": "Medium",
    "Orc War Chief": "Medium",
    "Lonely Sorrowsworn": "Medium",
    "Gnoll Flesh Gnawer": "Medium",
    "Dimetrodon": "Medium",
    "Soul Monger": "Medium",
    "Green Dragon Wyrmling": "Medium",
    "Wood Woad": "Medium",
    "Panther": "Medium",
    "Banshee": "Medium",
    "Yochlol": "Medium",
    "Spawn of Kyuss": "Medium",
    "Orc Nurtured One of Yurtrus": "Medium",
    "Animated Armor": "Medium",
    "Githyanki Supreme Commander": "Medium",
    "Galeb Duhr": "Medium",
    "Thorny": "Medium",
    "Star Spawn Seer": "Medium",
    "Shrieker": "Medium",
    "Mind Flayer Lich": "Medium",
    "Invisible Stalker": "Medium",
    "Swarm of Poisonous Snakes": "Medium",
    "Sahuagin": "Medium",
    "Mind Flayer Arcanist": "Medium",
    "Bodak": "Medium",
    "Fire Snake": "Medium",
    "Bronze Dragon Wyrmling": "Medium",
    "Deer": "Medium",
    "Nagpa": "Medium",
    "Gnoll Hunter": "Medium",
    "Quaggoth Spore Servant": "Medium",
    "Lemure": "Medium",
    "Adult Kruthik": "Medium",
    "Darkling Elder": "Medium",
    "Mule": "Medium",
    "Hobgoblin": "Medium",
    "Morkoth (in lair)": "Medium",
    "Deva": "Medium",
    "Needle Blight": "Medium",
    "Ghost": "Medium",
    "Sword Wraith Commander": "Medium",
    "Dybbuk": "Medium",
    "Duergar": "Medium",
    "Shadow Dancer": "Medium",
    "Thri-kreen": "Medium",
    "Duergar Screamer": "Medium",
    "Merfolk": "Medium",
    "Sea Spawn": "Medium",
    "Shadow": "Medium",
    "Giant Weasel": "Medium",
    "Kuo-toa Archpriest": "Medium",
    "Bheur Hag": "Medium",
    "Guard Drake": "Medium",
    "Stone Defender": "Medium",
    "Duergar Stone Guard": "Medium",
    "Kuo-toa Whip": "Medium",
    "Ettercap": "Medium",
    "Summer Eladrin": "Medium",
    "Abyssal Wretch": "Medium",
    "Orc Red Fang of Shargaas": "Medium",
    "Lizardfolk": "Medium",
    "Quaggoth Thonot": "Medium",
    "Deathlock": "Medium",
    "Lich": "Medium",
    "Babau": "Medium",
    "Mimic": "Medium",
    "Eidolon": "Medium",
    "Skeleton": "Medium",
    "White Abishai": "Medium",
    "Mastiff": "Medium",
    "Githyanki Knight": "Medium",
    "Slithering Tracker": "Medium",
    "Grell": "Medium",
    "Ghast": "Medium",
    "Harpy": "Medium",
    "Githzerai Enlightened": "Medium",
    "Tridrone": "Medium",
    "Hyena": "Medium",
    "Orc Claw of Luthic": "Medium",
    "Wererat": "Medium",
    "Nupperibo": "Medium",
    "Spectator": "Medium",
    "Gnoll Fang of Yeenoghu": "Medium",
    "Pteranodon": "Medium",
    "Red Abishai": "Medium",
    "Blue Abishai": "Medium",
    "Alhoon": "Medium",
    "Specter (poltergeist)": "Medium",
    "Star Spawn Mangler": "Medium",
    "Deep Rothe": "Medium",
    "Githyanki Warrior": "Medium",
    "Lizardfolk Shaman": "Medium",
    "Yuan-ti Malison": "Medium",
    "Orc Hand of Yurtrus": "Medium",
    "Skull Lord": "Medium",
    "Grick": "Medium",
    "Hungry Sorrowsworn": "Medium",
    "Hobgoblin Warlord": "Medium",
    "Flesh Golem": "Medium",
    "Stone Cursed": "Medium",
    "Earth Elemental Myrmidon": "Medium",
    "Revenant": "Medium",
    "Reef Shark": "Medium",
    "Githyanki Gish": "Medium",
    "Drow": "Medium",
    "Hobgoblin Captain": "Medium",
    "Gray Ooze": "Medium",
    "Sahuagin Priestess": "Medium",
    "Tanarukk": "Medium",
    "Tortle": "Medium",
    "Giant Wolf Spider": "Medium",
    "Black Abishai": "Medium",
    "Deathlock Mastermind": "Medium",
    "Shadow Demon": "Medium",
    "Morkoth": "Medium",
    "Copper Dragon Wyrmling": "Medium",
    "Drow Arachnomancer": "Medium",
    "Maw Demon": "Medium",
    "Vulture": "Medium",
    "Medusa": "Medium",
    "Shadow Mastiff": "Medium",
    "Vampire (warrior)": "Medium",
    "Fire Elemental Myrmidon": "Medium",
    "Alkilith": "Medium",
    "Swarm of Rats": "Medium",
    "Maurezhi": "Medium",
    "Giant Badger": "Medium",
    "Yuan-ti Pureblood": "Medium",
    "Swarm of Ravens": "Medium",
    "Deep Scion": "Medium",
    "Couatl": "Medium",
    "Piercer": "Medium",
    "Incubus": "Medium",
    "Yuan-ti Pit Master": "Medium",
    "Bugbear Chief": "Medium",
    "Green Hag": "Medium",
    "Death Dog": "Medium",
    "Drow House Captain": "Medium",
    "Air Elemental Myrmidon": "Medium",
    "Orc": "Medium",
    "Gnoll Witherling": "Medium",
    "Arcanaloth": "Medium",
    "Deinonychus": "Medium",
    "Gargoyle": "Medium",
    "Water Elemental Myrmidon": "Medium",
    "Nothic": "Medium",
    "Helmed Horror": "Medium",
    "Githyanki Kith'rak": "Medium",
    "Blue Dragon Wyrmling": "Medium",
    "Vampiric Mist": "Medium",
    "Bulezau": "Medium",
    "Neogi Master": "Medium",
    "Death Slaad": "Medium",
    "Yuan-ti Nightmare Speaker": "Medium",
    "Canoloth": "Medium",
    "Yuan-ti Mind Whisperer": "Medium",
    "Sea Hag": "Medium",
    "Spring Eladrin": "Medium",
    "Azer": "Medium",
    "Kuo-toa": "Medium",
    "Night Hag": "Medium",
    "Drow Shadowblade": "Medium",
    "Pony": "Medium",
    "Boar": "Medium",
    "Drow Inquisitor": "Medium",
    "Bullywug": "Medium",
    "Gray Slaad": "Medium",
    "Githzerai Anarch": "Medium",
    "Sword Wraith Warrior": "Medium",
    "Vampire Spawn": "Medium",
    "Skulk": "Medium",
    "Gloom Weaver": "Medium",
    "Goat": "Medium",
    "Choldrith": "Medium",
    "Xorn": "Medium",
    "Dolphin": "Medium",
    "Nabassu": "Medium",
    "Duergar Warlord": "Medium",
    "Giant Frog": "Medium",
    "Angry Sorrowsworn": "Medium",
    "Swarm of Insects": "Medium",
    "Red Dragon Wyrmling": "Medium",
    "Dryad": "Medium",
    "Duergar Soulblade": "Medium",
    "Ape": "Medium",
    "Peryton": "Medium",
    "Jackalwere": "Medium",
    "Amnizu": "Medium",
    "Firenewt Warrior": "Medium",
    "Ghoul": "Medium",
    "Mezzoloth": "Medium",
    "Oinoloth": "Medium",
    "Star Spawn Larva Mage": "Medium",
    "Silver Dragon Wyrmling": "Medium",
    "Mummy Lord": "Medium",
    "Quaggoth": "Medium",
    "Duodrone": "Medium",
    "Giant Wasp": "Medium",
    "Iron Cobra": "Medium",
    "Zombie": "Medium",
    "Aarakocra": "Medium",
    "Rust Monster": "Medium",
    "Half-Red Dragon Veteran": "Medium",
    "Gnoll": "Medium",
    "Black Bear": "Medium",
    "Duergar Mind Master": "Medium",
    "Vine Blight": "Medium",
    "Orc Eye of Gruumsh": "Medium",
    "Giant Crab": "Medium",
    "Yuan-ti Broodguard": "Medium",
    "Vampire": "Medium",
    "Male Steeder": "Medium",
    "Adult Oblex": "Medium",
    "Werebear": "Medium",
    "Duergar Xarrorn": "Medium",
    "Orog": "Medium",
    "Lich (in lair)": "Medium",
    "Erinyes": "Medium",
    "Mind Flayer": "Medium",
    "Cambion": "Medium",
    "Troglodyte": "Medium",
    "Kenku": "Medium",
    "Myconid Adult": "Medium",
    "Wraith": "Medium",
    "Mummy Lord (in lair)": "Medium",
    "Bronze Scout": "Medium",
    "Gibbering Mouther": "Medium",
    "Rutterkin": "Medium",
    "Grimlock": "Medium",
    "Black Dragon Wyrmling": "Medium",
    "Wight": "Medium",
    "Githzerai Zerth": "Medium",
    "Swarm of Quippers": "Medium",
    "Weretiger": "Medium",
    "Deathlock Wight": "Medium",
    "Mummy": "Medium",
    "Githzerai Monk": "Medium",
    "Lizard King/Queen": "Medium",
    "Orc Blade of Ilneval": "Medium",
    "Allip": "Medium",
    "Giant Poisonous Snake": "Medium",
    "Duergar Kavalrachni": "Medium",
    "Barbed Devil": "Medium",
    "Merrenoloth": "Medium",
    "Dhergoloth": "Medium",
    "Bugbear": "Medium",
    "Gold Dragon Wyrmling": "Medium",
    "Succubus": "Medium",
    "White Dragon Wyrmling": "Medium",
    "Tortle Druid": "Medium",
    "Meazel": "Medium",
    "Hobgoblin Devastator": "Medium",
    "Autumn Eladrin": "Medium",
    "Giff": "Medium",
    "Swarm of Cranium Rats": "Medium",
    "Werewolf": "Medium",
    "Scarecrow": "Medium",
    "Flind": "Medium",
    "Merregon": "Medium",
    "Vampire (spellcaster)": "Medium",
    "Bearded Devil": "Medium",
    "Narzugon": "Medium",
    "Duergar Hammerer": "Medium",
    "Ultroloth": "Medium",
    "Monodrone": "Medium",
    "Quadrone": "Medium",
    "Gnoll Pack Lord": "Medium",
    "Berbalang": "Medium",
    "Doppelganger": "Medium"
}

small_monsters = {
    "Grung": "Small",
    "Manes": "Small",
    "Derro": "Small",
    "Myconid Sprout": "Small",
    "Ice Mephit": "Small",
    "Goblin Boss": "Small",
    "Baboon": "Small",
    "Giant Fire Beetle": "Small",
    "Awakened Shrub": "Small",
    "Kobold Dragonshield": "Small",
    "Octopus": "Small",
    "Korred": "Small",
    "Derro Savant": "Small",
    "Goblin": "Small",
    "Darkmantle": "Small",
    "Dretch": "Small",
    "Kobold Inventor": "Small",
    "Blood Hawk": "Small",
    "Wretched Sorrowsworn": "Small",
    "Winged Kobold": "Small",
    "Boggle": "Small",
    "Kobold Scale Sorcerer": "Small",
    "Smoke Mephit": "Small",
    "Neogi": "Small",
    "Meenlock": "Small",
    "Giant Rat": "Small",
    "Redcap": "Small",
    "Steam Mephit": "Small",
    "Star Spawn Grue": "Small",
    "Grung Elite Warrior": "Small",
    "Magma Mephit": "Small",
    "Young Kruthik": "Small",
    "Kobold": "Small",
    "Grung Wildling": "Small",
    "Magmin": "Small",
    "Mud Mephit": "Small",
    "Flying Sword": "Small",
    "Jackal": "Small",
    "Nilbog": "Small",
    "Eagle": "Small",
    "Darkling": "Small",
    "Choker": "Small",
    "Chitine": "Small",
    "Vegepygmy": "Small",
    "Spined Devil": "Small",
    "Xvart": "Small",
    "Flumph": "Small",
    "Xvart Warlock of Raxivort": "Small",
    "Twig Blight": "Small",
    "Vegepygmy Chief": "Small",
    "Dust Mephit": "Small",
    "Svirfneblin": "Small",
    "Giant Centipede": "Small",
    "Cockatrice": "Small"
}

tiny_monsters = {
    "Cat": "Tiny",
    "Intellect Devourer": "Tiny",
    "Young Faerie Dragon": "Tiny",
    "Pixie": "Tiny",
    "Imp": "Tiny",
    "Vargouille": "Tiny",
    "Weasel": "Tiny",
    "Adult Faerie Dragon": "Tiny",
    "Raven": "Tiny",
    "Gazer": "Tiny",
    "Quasit": "Tiny",
    "Crab": "Tiny",
    "Bat": "Tiny",
    "Sprite": "Tiny",
    "Badger": "Tiny",
    "Crawling Claw": "Tiny",
    "Demilich": "Tiny",
    "Oblex Spawn": "Tiny",
    "Neogi Hatchling": "Tiny",
    "Frog": "Tiny",
    "Lizard": "Tiny",
    "Cranium Rat": "Tiny",
    "Will-o-wisp": "Tiny",
    "Demilich (in lair)": "Tiny",
    "Pseudodragon": "Tiny",
    "Homunculus": "Tiny",
    "Quipper": "Tiny",
    "Sea Horse": "Tiny",
    "Spider": "Tiny",
    "Velociraptor": "Tiny",
    "Flying Snake": "Tiny",
    "Scorpion": "Tiny",
    "Rat": "Tiny",
    "Poisonous Snake": "Tiny",
    "Flameskull": "Tiny",
    "Quickling": "Tiny",
    "Hawk": "Tiny",
    "Stirge": "Tiny",
    "Owl": "Tiny",
    "Slaad Tadpole": "Tiny"
}


# sizes = []
# monster_names = []

# for monster in monster_data:
#     monster_names.append(monster)

# for monster in monster_data:
#     sizes.append(monster_data[monster]["size"])

# dictionary = dict(zip(monster_names, sizes))

dictionary = sorted(monster_data, key=monster_data.get)

print("{")
for monster in dictionary:
    print('"' + monster + '"' + ": " + '"' +
          monster_data.get(monster) + '"' + ",")
print("}")
